# Generated by Django 4.0.1 on 2022-01-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSkills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('proficiency', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
    ]
